# Generated by Django 4.0.4 on 2022-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('userId', models.UUIDField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
